### ISSUE TITLE
BetterXP-Mending gives XP per crafting time not per completion.

### ISSUE THREAD

**Issue by BrianGriff1n** [MikeyPdog/TLD-Minimods#1]
If I use only half an hour to craft I get the same amount of XP as if crafting for 8 hours straight.

Example: 
1. Crafting rabbit hat for 8 h in one go gives one 'unit' of XP (about 2 mm on my screen, Mending level 3).
2. Crafting the rabbit hat in 16 half hour portions, gives 16 (!) 'units' of XP (about 26 mm on my screen).

**Comment by MikeyPdog** [comment]
Thanks for reporting! Fixed in latest release (3.4).
